// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfmyaioxcxndsqkblnwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbXlhaW94Y3huZHNxa2Jsbnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTMyNDQsImV4cCI6MjA2MzU4OTI0NH0.9lmvw5iwo2uqIscEoRU9jhlg7M8lW-i3EojXgG5Bbhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);